version: '3.8'

services:
  cash-stuffing:
    build: .
    container_name: cash_stuffing_app
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - budget_data:/data

volumes:
  budget_data:
